### ISSUE TITLE
Access to Rate Limit Headers

### ISSUE THREAD

**Issue by bradmkjr** [djchen/oauth2-fitbit#11]
I would appreciate if following a request the rate limit, amount remaining and time remaining where available by a method call on the provider.

https://dev.fitbit.com/docs/basics/#rate-limits

I want to suggest something like the following, but want to leave it up to you to match your style and the best interest of the rest of the users.

```

    /**
     * @var string
     */
    protected $limit;

    /**
     * @var string
     */
    protected $remaining;

    /**
     * @var string
     */
    protected $reset;

protected function checkResponse(ResponseInterface $response, $data)
    {

        $this->limit = $response->getHeader('Fitbit-Rate-Limit-Limit')[0];
        $this->remaining = $response->getHeader('Fitbit-Rate-Limit-Remaining')[0];
        $this->reset = $response->getHeader('Fitbit-Rate-Limit-Reset')[0];

        if (!empty($data['errors'][0])) {
            $message = $data['errors'][0]['errorType'] . ': ' . $data['errors'][0]['message'];
            throw new IdentityProviderException($message, $response->getStatusCode(), $data);
        }
    }

public function getRateLimit(){
            return $this->limit;
}

public function getRateRemaining(){
            return $this->remaining;
}

public function getRateReset(){
            return $this->reset;
}
```

If you would like me to test and do a formal pull request I'm willing, if that will help this get integrated faster.

Thanks
Brad

**Comment by djchen** [comment]
Hi Brad,

I think this is a great idea. I'd be totally open to integrating this in and a Pull Request is highly appreciated.

Cheers,
Dan

**Comment by bradmkjr** [comment]
Thank you!
