### ISSUE TITLE
Invalid authorization header

### ISSUE THREAD

**Issue by ghost** [djchen/oauth2-fitbit#12]
When using the library to authorize my application with Fitbit, I get the following error displayed after callback (the callback page is the same URL as the page calling the example code from README):

"invalid_client: Invalid authorization header. Client secret invalid. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process."

The error is generated by this code:

 // Try to get an access token using the authorization code grant.
        $accessToken = $provider->getAccessToken('authorization_code', [
            'code' => $_GET['code']
        ]);

The callback URL looks like this: "test.php?state=otrqVmQ3lvKQdiXxV8YVO5HyJQCwGvmj&code=40354c250f865fb45232ac1f3d1f6162083dae0f" so isset($_GET['code']) is true and so that try statement is attempted. I'm just using the example code provided in the README, changing only the client ID, client secret, and the callback URL (test.php is both the entry page for this test and the callback URL). 

I read (https://twittercommunity.com/t/puzzling-invalid-authorization-header-error-when-working-with-update-with-media/331) that maybe the client library was missing a URL encoding for the headers. Seems unlikely, but instead of trying to figure out what I'm doing wrong I was hoping you could help?!

**Comment by djchen** [comment]
Have you verified the client secret you specified exactly matches the one from dev.fitbit.com?

**Comment by ghost** [comment]
I apologize, I'm an idiot. I passed right over the "Client secret invalid" and didn't bother to check. That's what it was. Sorry for posting this, but thank you for taking the time to help, I really appreciate it!

**Comment by djchen** [comment]
No worries, I do it all the time :)
