### ISSUE TITLE
GrantFactory syntax error

### ISSUE THREAD

**Issue by daniel-luna** [djchen/oauth2-fitbit#13]
When using the library to authorize my application with Fitbit, I get the following error displayed after callback

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /usr/home/BRCL7V3Lz44O/testbihealth.cat/web/devices/fitbit2/vendor/league/oauth2-client/src/Grant/GrantFactory.php on line 85

(after authorize my Fitbit app I'm being redirected to my callback page, but i get this error)

I've installed oauth2-fitbit via composer and I've just created a single page to run the code (code from README)

Am I missing something?

**Comment by djchen** [comment]
Hi,

I was unfortunately not able to reproduce this. That seems like there is a syntax error in the League OAuth2 client that we use under the hood. Can you run "composer update" and try again?

**Comment by daniel-luna** [comment]
Hi,
the problem was on the PHP version of the server.
Solved! Thanks!
