### ISSUE TITLE
Cant access response data

### ISSUE THREAD

**Issue by acndur1a** [djchen/oauth2-fitbit#14]
I am trying to access PSR 7 response object but wont give me access to any index

```
                $rxs = $response->getBody();
                var_dump($rxs);
                $headers = $response->getHeaders();
                foreach ($headers as $name => $values) {
                    echo $name . ": " . implode(", ", $values);
                }  

```

Also tried using $response['encodedId'] or $response[0] or $response[0]['encodedId'] all return empty... from below response

Anyway I can return json?

**Comment by djchen** [comment]
How are you making the request? Can you paste a little bit more of the code?

**Comment by djchen** [comment]
Heres an example of what I think you were trying to do?

```
        $request = $provider->getAuthenticatedRequest(
            'GET',
            'https://api.fitbit.com/1/user/-/profile.json',
            $accessToken
        );
        $response = $provider->getResponse($request);
        echo $response['user']['encodedId'];
```

**Comment by acondurache** [comment]
I tried the above but Im getting astring in front before a array... see below for the response I get using your code $response['user']['encodeId']

eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NjA3MDkwOTcsInNjb3BlcyI6InJ3ZWkgcnBybyByaHIgcmxvYyByc2xlIHJzZXQgcmFjdCByc29jIiwic3ViIjoiNEg4NU5WIiwiYXVkIjoiMjI3UUNXIiwiaXNzIjoiRml0Yml0IiwidHlwIjoiYWNjZXNzX3Rva2VuIiwiaWF0IjoxNDYwNzA1NDk3fQ.mwMBJPvZXES_Q0pkIFWXI-tsfJPa6zI9J9oMaGvz7vY 4881f112ccf70aceaf2bd1b3f067ac23ec0d140585820f85f5a400cd10340507 1460709097 not expired array ( 'encodedId' => '4HX5XX', 'displayName' => 'andrew', )4H85NV

**Comment by acndur1a** [comment]
Works
