### ISSUE TITLE
Not an issue, question

### ISSUE THREAD

**Issue by ljhardy** [djchen/oauth2-fitbit#16]
Can you help me with the process for setting the Accept-Language header to change the responses from Metric?  

header('Accept-Language ' . "en-US");

I'm confused as to whether this is set when getting the token or when doing the request for data.

Thanks, Len

**Comment by djchen** [comment]
When making a request, use the 4th parameter to specify the headers you want to send:

```
        $request = $provider->getAuthenticatedRequest(
            'GET',
            Fitbit::BASE_FITBIT_API_URL . '/1/user/-/profile.json',
            $accessToken,
            ['headers' => ['Accept-Language' => 'en_US'], ['Accept-Locale' => 'en_US']]
        );
```

Note its en_US and not en-US (underscore instead of dash)
https://dev.fitbit.com/docs/basics/#localization

**Comment by ljhardy** [comment]
Thanks Dan.  Appreciate it!

**Comment by djchen** [comment]
You are welcome!
