### ISSUE TITLE
Fatal error: Class 'djchen\OAuth2\Client\Provider\Fitbit' not found

### ISSUE THREAD

**Issue by nunocsilva** [djchen/oauth2-fitbit#25]
Hi,
I'm new to composer and am having some issues.
I've installed the library:
composer require djchen/oauth2-fitbit
and it worked.

Then I created a PHP file with this:
use djchen\OAuth2\Client\Provider\Fitbit;
$provider = new Fitbit([
    'clientId'          => 'xxx',
    'clientSecret'      => 'xxx',
    'redirectUri'       => 'xxx'
]);

and got the error:
Fatal error: Class 'djchen\OAuth2\Client\Provider\Fitbit' not found in xxx 

Can someone help me please?
Thanks, 
Sofia

**Comment by djchen** [comment]
Make sure you require the vendor autoload.php
See https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by ahmad-hosseini** [comment]
Hi @djchen ,
I am having a similar issue. I get the exact same error. I have called composer update and composer dump-autoload, yet the problem still persits. 

I have the following in my composer.json 
`    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },`

Any help would be greatly appreciated.

**Comment by djchen** [comment]
It doesn't look like you are requiring the library in your composer.json.
See: https://getcomposer.org/doc/01-basic-usage.md#the-require-key

**Comment by ahmad-hosseini** [comment]
@djchen ,
I am, i only showed everything relevant to the auto loader as i firmly believe the issue is to do with the auto loader.

Sorry for the confusion. Here is the full composer.json if you would like to view it. 
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "djchen/oauth2-fitbit": "^1.0",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}
