### ISSUE TITLE
Call to undefined method Fitbit::parsedResponse()

### ISSUE THREAD

**Issue by HoverBaum** [djchen/oauth2-fitbit#29]
Trying to get the example from the readme to work I succeded pretty far until ` $response = $provider->getParsedResponse($request);` to which I get the output:

```
Fatal error: Call to undefined method djchen\OAuth2\Client\Provider\Fitbit::parsedResponse()
```

Which seems to tell me that a function I want to invoke is missing. Looked through the sourcecode and could find no reference to said function either. 
At a loss as to how I can make this work.

**Comment by djchen** [comment]
I think you have the 0.3.x version of the library installed.
If thats the case, follow the README from here: https://github.com/djchen/oauth2-fitbit/tree/0.3.1
Or you can alternatively install the 1.0.0-beta2 version and keep the code as is.

**Comment by HoverBaum** [comment]
How could I check which version I am using and update?

Totally new to composer and just ran the `composer require djchen/oauth2-fitbit` I found in the README.

**Comment by djchen** [comment]
`composer show` will print a list of dependent libraries and their versions.

https://getcomposer.org/doc/03-cli.md#show

**Comment by HoverBaum** [comment]
Thanks for the help. Got it to work now. Think I was confused at the end why composer would install the up-to-date version, not realizing that the main README is for a beta version.

**Comment by vikput** [comment]
Trying to use refresh token to get new access_token but it giving and error Call to undefined method stdClass::hasExpired(). Following your example code but having no luck can u please help.

**Comment by djchen** [comment]
Please open a new issue and provide more information on how to reproduce the same setup. Thanks!
