### ISSUE TITLE
Changing Scope

### ISSUE THREAD

**Issue by SeanMee86** [djchen/oauth2-fitbit#30]
Hi, I'm trying to change the scope from profile to heartrate so that I can pass /1/user/-/activities/heart/date/today/7d.json into the Base url.  I've tried changing this
protected function getDefaultScopes()
    {
        return ['activity', 'heartrate', 'location', 'profile', 'settings', 'sleep', 'social', 'weight'];
    }

to this
protected function getDefaultScopes()
    {
        return ['heartrate'];
    }

and the base fitbit api url in the Fitbit.php file as well as my file containing the example from the read me and all I get is a NULL result.  Thanks in advance for any help you can give me.

**Comment by djchen** [comment]
This wiki page details how to override the scopes:
https://github.com/djchen/oauth2-fitbit/wiki/Specifying-Scopes

I'm not sure I understand the need to change the base url. Can you describe what you want to do?

**Comment by SeanMee86** [comment]
Sorry, not change the base url, but the extension so that I get heart rate data instead of profile data.  in the php files i'm passing /1/user/-/profile.json onto the base url, but I need to pass this /1/user/-/activities/heart/today/7d.json.  When I do I'm getting a value of null, but when I check on postman all the data is there.

**Comment by djchen** [comment]
Can you paste the code you're using?

You should be able to do something like this:

```
        $request = $provider->getAuthenticatedRequest(
            Fitbit::METHOD_GET,
            Fitbit::BASE_FITBIT_API_URL . '/1/user/-/activities/heart/date/today/7d.json',
            $accessToken
        );
        $response = $provider->getParsedResponse($request);
        print_r($response);
```

**Comment by SeanMee86** [comment]
... I wasn't printing the response.  Sorry! Thank you so much for the quick replies!

**Comment by djchen** [comment]
Happy to help!
