### ISSUE TITLE
i want get data fitbit no callback

### ISSUE THREAD

**Issue by napatchanapai** [djchen/oauth2-fitbit#35]
hi, i  want get data fitbit no callback becase i use loop pull data from last update date to now date  and save data to database.
 
but i have problem is after pull data it callback to url. it can't loop to now date.
 
please help me.  thank you.

**Comment by djchen** [comment]
I'm not sure what you mean "pull data it callback to url".
Have you already obtained a access token (bearer token) at this point?
Can you provide more information about the problem including steps to reproduce and a code snippet?
