### ISSUE TITLE
How to do subscriptions ?

### ISSUE THREAD

**Issue by sufianetaouil** [djchen/oauth2-fitbit#37]
Hello everyone,
I'm trying to create a subscription system but i'm stuck,
First thing i did is adding a subscribing to my application and validating it with the 2 requests step, then i'm using this code on my page to add subscriptions : 
```
`if(isset($_GET['addsubscription']) && $_SESSION['token'] != null && !$_SESSION['token']->hasExpired())
{
	$request = $provider->getAuthenticatedRequest(
			'POST',
			'https://api.fitbit.com/1/user/-/activities/apiSubscriptions/202.json',
			$_SESSION['token']
		);
	$response = $provider->getResponse($request);
	$parsedResponse = $provider->parseResponse($response);
	var_dump($parsedResponse);

}`
```
202 is the id of the subscriber,
The code above doesn't show anything because the callback url of the application is different from the subscriber endpoint url, but that's not a problem since i don't need to see response on the page, but what i need to see is a new "Stats" or something on the application page that shows me that there is something going on, i also runned this code : 
```
`$request = $provider->getAuthenticatedRequest(
			'GET',
			'https://api.fitbit.com/1/user/-/activities/apiSubscriptions.json',
			$_SESSION['token']
		);
	$response = $provider->getResponse($request);
	$parsedResponse = $provider->parseResponse($response);
	var_dump($parsedResponse);`

```
And the result is 
`array(1) { ["apiSubscriptions"]=> array(0) { } }`

Empty like no one subscribed, any one has an idea about what's going on ?
Thanks.
P.S : the account that subscribed is the owner of the application, maybe that's the cause ?

**Comment by djchen** [comment]
What is the response to the first request to add the subscriber?

**Comment by sufianetaouil** [comment]
@djchen The endpoint url is an online website, and the application callback url is my localhost website, when i add a subscription from the online website with the first script it redirects me to localhost

**Comment by sufianetaouil** [comment]
@djchen I moved the adding subscription code to localhost as well (still the endpoint url is online), and this time when i run the code first time, it returns page ok, when i refresh the page it returns 409 error conflict, meaning that the user is already subscribed, but when i go to the stats it's empty, is-it normal that we can't view the subscribed users ? Maybe the stats are about the delivering not about the users ?
EDIT : This is weird, even though i get 409 error (conflict), when i lunch a request with the code : 
`	$request = $provider->getAuthenticatedRequest(
			'GET',
			'https://api.fitbit.com/1/user/-/activities/apiSubscriptions.json',
			$_SESSION['token']
		);
	$response = $provider->getResponse($request);
	$parsedResponse = $provider->parseResponse($response);
	var_dump($parsedResponse);`

All I get is this : 
`array(1) { ["apiSubscriptions"]=> array(0) { } }`

**Comment by sufianetaouil** [comment]
Ok i solved that problem (i'm not sure how but it was kinda dump), now i'm stuck in making the background request to the page that will fetch the changes, since the fitbit system cuts the connection to the webhook after 3 seconds which is not enough, i have to save the json result then make the other requests in another page, so what i'm thinking is to use curl inside the webhook page to call another page that will process the result coming from fitbit, but unfortunately i was'nt able to use curl nether any known methods of sending get/post requests between php pages :/

**Comment by djchen** [comment]
You should use a queuing system of some sort to deal with that. When you get pinged by Fitbit on the callback, throw a message onto a queue and have workers that handle processing it.

Since that is outside the scope of this library, I'm going to close this.
