### ISSUE TITLE
getting error "Forbidden" from IdentityProviderException

### ISSUE THREAD

**Issue by bretzelpretzel** [djchen/oauth2-fitbit#38]
I had been using your code for a while and it was working very well. Now all of a sudden, I'm getting the error "Forbidden" whenever I try to login from the IdentityProviderException clause. Any ideas on how to fix this? I'm at a complete loss, and with a one word error message, I'm not sure how to proceed. Thank you in advance!

Brett

**Comment by bretzelpretzel** [comment]
I've now figured out that the error is coming from when the code runs this line:

$accessToken = $provider->getAccessToken('authorization_code', ['code' => $_GET['code']]);

Thank you,

Brett

**Comment by djchen** [comment]
Sorry about the delayed response, I just got back from vacation today.

Let me give a go tonight and see what I can find out.

**Comment by bretzelpretzel** [comment]
Hey, thanks for offering to help. Any luck so far? I just really don't know how to troubleshoot beyond where I am now.

**Comment by djchen** [comment]
No, I wasn't able to reproduce the issue that you described. It works for me on my test app and a newly registered app as well.

**Comment by bretzelpretzel** [comment]
Here is my code at the start...the echo 'still going...' never gets displayed, so the error must be coming from the get access token line...

```
<?php namespace djchen\OAuth2\Client\Provider;
require __DIR__.'/vendor/autoload.php';
require __DIR__.'/vendor/oauth2-fitbit-master/src/Provider/Fitbit.php';
require __DIR__.'/vendor/oauth2-fitbit-master/src/Provider/FitbitUser.php';
use djchen\Oauth2\Client\Provider\Fitbit;
use djchen\Oauth2\Client\Provider\FitbitUser;
$provider = new Fitbit([
    'clientId'          => '****',
    'clientSecret'      => '****',
    'redirectUri'       => '****'
]);
    ob_start(); 
    ini_set('session.save_path',realpath(dirname($_SERVER['DOCUMENT_ROOT']) . '/var/php_sessions'));
    session_start();
if (!isset($_GET['code'])) {
    $authorizationUrl = $provider->getAuthorizationUrl();
    $_SESSION['oauth2state'] = $provider->getState();
    header('Location: ' . $authorizationUrl);
    exit;
} elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {
    unset($_SESSION['oauth2state']);
    header("Location: /failure.php");
    exit('Invalid state');
} else {
	echo "working here...";
    try {
		$accessToken = $provider->getAccessToken('authorization_code', ['code' => $_GET['code']]);
		echo "still going...";
```

I'm not sure if that helps since it is awfully similar to your initial code...Thanks in advance for trying!

**Comment by djchen** [comment]
You're code should not be namespace'd to djchen\OAuth2....

What you want to do is load the library via composer `composer require djchen/oauth2-fitbit`
and then only `require 'vendor/autoload.php';`. You don't need to require the Fitbit.php and FitbitUser.php files.

**Comment by bretzelpretzel** [comment]
Hmmmm. perhaps I need a lesson on using composer for a live website...I was
able to make that work on my computer when using WAMP, but when I put it on
a live website, I just copied all of the folders it had loaded.

When I erase the namespace line and the require Fitbit.php and
FitbitUser.php, I get the following error:

Uncaught Error: Class 'djchen\Oauth2\Client\Provider\Fitbit' not found

**Comment by bretzelpretzel** [comment]
i understand closing the ticket, but my problem is unfortunately not resolved. I had set up my dependencies by doing composer locally and pushing over FTP. after removing those lines you suggested, I get a series of errors....any explanations as to why that might be? 

Regardless, the code had been working for weeks and just suddenly stopped....I was hoping for a better solution if you have any other ideas. thanks

**Comment by djchen** [comment]
The issue you're having is not one with the library. I think you should seek help with using Composer somewhere more appropriate.

Yes, I understand it was working however that is not a supported method of use.
