### ISSUE TITLE
How to get hold of expires in? Docs?

### ISSUE THREAD

**Issue by kgrosvenor** [djchen/oauth2-fitbit#40]

**Comment by djchen** [comment]
See `echo $accessToken->getExpires()` in the readme example.

**Comment by kgrosvenor** [comment]
What about expires_in

**Comment by djchen** [comment]
That is it.

**Comment by kgrosvenor** [comment]
Is it in seconds, or is a date, im seeing a long unix timestamp, however
for now i just hard coded in the fitbit default, i was checking the code
over and i noticed something to do with getExpires, but no
getExpiresInSeconds, can this be set also?

**Comment by djchen** [comment]
I suggest looking at the upstream [oauth2-client](https://github.com/thephpleague/oauth2-client/) library that this is a provider for.
https://github.com/thephpleague/oauth2-client/blob/master/src/Token/AccessToken.php#L144

If you just want to check if the token is expired, there is a method to do just that:
https://github.com/thephpleague/oauth2-client/blob/master/src/Token/AccessToken.php#L169

**Comment by kgrosvenor** [comment]
Thanks, can expiresIn : seconds be passed in the Fitbit constructor, as an
array option?

Thanks for your time

**Comment by djchen** [comment]
Can you post some example code of what you are trying to do?
