### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by lewishowles** [djchen/oauth2-fitbit#42]
**Edited**

When doing a fresh install, composer was getting League/OAuth2 version 2.4.0 based on the "~2.2" value in package.json, which this package seems to be incompatible with.

Declaration of `djchen\OAuth2\Client\Provider\Fitbit::getResourceOwnerDetailsUrl(League\OAuth2\Client\Token\AccessToken $token)` must be compatible with `League\OAuth2\Client\Provider\AbstractProvider::getResourceOwnerDetailsUrl(League\OAuth2\Client\Token\AccessTokenInterface $token)`

I managed to solve the issue by installing League/OAuth2:2.2.0 first, then installing this package.

Thanks!

**Comment by djchen** [comment]
It looks like there is indeed a compatibility issue with OAuth2-Client 2.4.x. I'll update the composer.json to pin it to 2.3.x for now. Thanks for reporting!

**Comment by djchen** [comment]
Looks like they caught that particular issue upstream and fixed it in 2.4.1 release:
https://github.com/thephpleague/oauth2-client/releases/tag/2.4.1

However I see an error when trying to exchange the authorization code.
Reverting back to 2.3.x seems to do the trick.
