### ISSUE TITLE
Refreshing the Access Token

### ISSUE THREAD

**Issue by ljhardy** [djchen/oauth2-fitbit#5]
This is certainly not a problem with your library, but with my understanding.  I ran the first part of your example and it worked great, I stored the access token and the refresh token to disk.  My use case is such that only the first time authenticating, and storing the tokens, all happen via the web.  All other accesses will happen on a schedule, run from a server, accessing the tokens.

My understanding is that Fitbit requires a refreshed token for each access.  I am struggling with your example refresh logic.  I'm able to read the access and the refresh token from disk and I know at this point that the access token is expired and needs to be refreshed.  I don't understand thIs part:

  $newAccessToken = $provider->getAccessToken('refresh_token', [
        'refresh_token' => $existingAccessToken->getRefreshToken()

The $existingAccessToken was just read from disk and doesn't have the getRefreshToken method available to it?  What am I missing here?

Thanks, Len

$provider = new djchen\OAuth2\Client\Provider\Fitbit([
    'clientId'          => '{fitbit-oauth2-client-id}',
    'clientSecret'      => '{fitbit-client-secret}',
    'redirectUri'       => 'https://example.com/callback-url'
]);

$existingAccessToken = getAccessTokenFromYourDataStore();

if ($existingAccessToken->hasExpired()) {
    $newAccessToken = $provider->getAccessToken('refresh_token', [
        'refresh_token' => $existingAccessToken->getRefreshToken()
    ]);

```
// Purge old access token and store new access token to your data store.
```

}

**Comment by djchen** [comment]
I assume you have figured this out. I just wanted to add that for this

> My understanding is that Fitbit requires a refreshed token for each access.

You only need to refresh the access token if it has expired, which is after 1 hour you first obtained it from Fitbit. This is why in the example "pseudocode" it first checks if it has expired or not.

**Comment by ljhardy** [comment]
Is there harm in refreshing for each access to eliminate the complexity of testing for expiration?

**Comment by djchen** [comment]
No. However testing for expiration is very straightforward. When you get the access token, you will also get the Unix timestamp for when it expires and its just a matter of doing a time() > $tokenExpirationTime.

**Comment by ljhardy** [comment]
Thanks Dan.  I did this and it's working fine.

Len

On Mon, Feb 1, 2016 at 12:27 AM, Dan Chen notifications@github.com wrote:

> No. However testing for expiration is very straightforward. When you get
> the access token, you will also get the Unix timestamp for when it expires
> and its just a matter of doing a time() > $tokenExpirationTime.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/djchen/oauth2-fitbit/issues/5#issuecomment-177801092.

## 

Len Hardy
Bartlett, IL
USA

http://www.firehole.us
http://www.lenhardy.com

**Comment by istvanskeri** [comment]
Are you also storing the expiration time in the database then?
