### ISSUE TITLE
OAuth 2.0 Client Provider Libraries

### ISSUE THREAD

**Issue by zembrowski** [djchen/oauth2-fitbit#7]
Do you plan to add `oauth2-fitbit` to the [third party providers list](https://github.com/thephpleague/oauth2-client/blob/master/README.PROVIDERS.md)?

**Comment by djchen** [comment]
Great idea! I'll send them a PR shortly.

**Comment by djchen** [comment]
Fixed by https://github.com/thephpleague/oauth2-client/pull/484
Thanks again
